name: Pull Request

on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - run: npm test
